### ISSUE TITLE
'Settings' object has no attribute 'ONELOGIN_SAML_SETTINGS'

### ISSUE THREAD

**Issue by mbk4** [penn-state-dance-marathon/python3-saml-django#13]
Hi, when I access saml login page I get an error:
```
'Settings' object has no attribute 'ONELOGIN_SAML_SETTINGS'
```

I don't see any configuration for for this attribute, what can be the problem?

Python 3.9.10, Django 4.0.1

```
Internal Server Error: /saml/login
Traceback (most recent call last):
  File "/home/jlr/git/ciara_software_upgrade/ciara_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jlr/git/ciara_software_upgrade/ciara_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jlr/git/ciara_software_upgrade/ciara_project/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jlr/git/ciara_software_upgrade/ciara_project/venv/lib/python3.9/site-packages/django_saml/views.py", line 39, in login
    saml_auth = OneLogin_Saml2_Auth(req, old_settings=settings.ONELOGIN_SAML_SETTINGS)
  File "/home/jlr/git/ciara_software_upgrade/ciara_project/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 85, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ONELOGIN_SAML_SETTINGS'
```

**Comment by ngearhart** [comment]
Hi, can you confirm that `django_saml` is in your `INSTALLED_APPS`? `ONELOGIN_SAML_SETTINGS` is populated when the app is loaded by Django.

**Comment by mbk4** [comment]
@ngearhart thank you for the reply. Yes it is there:
```
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'channels',
    'TestCaseManager.apps.TestCaseManagerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_saml'
]
```

**Comment by mbk4** [comment]
Library appears to default to expecting a `ONELOGIN_SAML_SETTINGS` to be included in a Django app's `settings.py`. I don't see this in documentation, is this expected behaviour? Is there a particular format that can be passed to this constant in order to enable SAML, alternatively to the methods mentioned in the README? 

Adding following line to `setting.py`
```
ONELOGIN_SAML_SETTINGS = None
```
seems to get rid this error:
```
'Settings' object has no attribute 'ONELOGIN_SAML_SETTINGS'
```

But another problem arises, probably connected to this one, please take a look if you can:
```
Internal Server Error: /saml/login
Traceback (most recent call last):
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/django_saml/views.py", line 39, in login
    saml_auth = OneLogin_Saml2_Auth(req, old_settings=settings.ONELOGIN_SAML_SETTINGS)
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/onelogin/saml2/auth.py", line 59, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/onelogin/saml2/settings.py", line 119, in __init__
    raise e
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/onelogin/saml2/settings.py", line 117, in __init__
    valid = self.__load_settings_from_file()
  File "/home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/onelogin/saml2/settings.py", line 252, in __load_settings_from_file
    raise OneLogin_Saml2_Error(
onelogin.saml2.errors.OneLogin_Saml2_Error: Settings file not found: /home/jlr/git/ciara_software_upgrade_3.9/ciara_project/venv/lib/python3.9/site-packages/settings.json
```

What is this  `settings.json` file and where should it be placed?

**Comment by ngearhart** [comment]
Can you provide your SAML settings? Make sure to censor any possibly secure data like certificates/keys/specific URLS.

This library populates `ONELOGIN_SAML_SETTINGS` for you on app load. You do not need to set it yourself.

**Comment by mbk4** [comment]
My SAML settings from `settings.py`:
```
SAML_SP = {
    "entityId": "https://localhost/saml/metadata/",
    "assertionConsumerService": {
        "url": "https://localhost/saml/acs/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
        "url": "https://localhost/saml/sls/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
    # "x509cert": "<can also be loaded by file, see SAML_BASE_DIRECTORY>",
    # "privateKey": "<can also be loaded by file, see SAML_BASE_DIRECTORY>"
}

# Build paths inside the project like this: Path(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

SAML_IDP_FILE = os.path.join(BASE_DIR, 'federationmetadata.xml')
SAML_DESTINATION_HOST = 'http://example.com/'  #changed url
SAML_DESTINATION_HTTPS = False
SAML_DESTINATION_PORT = '80'
ONELOGIN_SAML_SETTINGS = None
```

**Comment by ngearhart** [comment]
I apologize for the late reply but I have not been able to discover the issue yet. I am still working on it

**Comment by mbk4** [comment]
No problem take your time, I found a working workaround:

`settings.py`:
```
SAML_SP = {
    "entityId": "https://localhost/saml/metadata/",
    "assertionConsumerService": {
        "url": "https://localhost/saml/acs/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
        "url": "https://localhost/saml/sls/",
        # DO NOT CHANGE THIS
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
}

AUTHENTICATION_BACKENDS = [
    'django_saml.backends.SamlUserBackend'
]

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent
SAML_IDP_FILE = os.path.join(BASE_DIR, 'federationmetadata.xml')
SAML_DESTINATION_HOST = 'localhost'
SAML_DESTINATION_HTTPS = True
SAML_DESTINATION_PORT = '443'
SAML_LOGIN_REDIRECT = '/'
ONELOGIN_SAML_SETTINGS = None
SAML_BASE_DIRECTORY = os.path.join(BASE_DIR, 'saml')
SAML_USERNAME_ATTR = 'UserName'
SAML_DEBUG = True
SAML_CREATE_USER = True
SAML_UPDATE_USER = False

SAML_ATTR_MAP = [
    ('email', 'Email'),
    ('username', 'UserName'),
    ('first_name', 'FirstName'),
    ('last_name', 'LastName')
]
```

`django_project/venv/lib/python3.10/site-packages/settings.json`:
```
{
  "strict": false,
  "debug": true,
  "sp": {
    "entityId": "https://localhost/metadata/",
    "assertionConsumerService": {
      "url": "https://localhost/saml/acs/",
      "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
      "url": "https://localhost/saml/sls/",
      "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
  },
  "idp": {
    "entityId": "http://sso.connect.com/adfs/services/trust",
    "singleSignOnService": {
      "url": "https://sso.connect.com/adfs/ls/"
    },
    "singleLogoutService": {
      "url": "https://sso.example.com/adfs/ls/"
    },
    "x509cert": "<my_key_hidden>"
  }
}
```

Django was complaining that it was missing some optional parameters in `settings.py` that's why I have that much info set there. Also the `IDP` and `SP` configs seem to be required in two places: in `settings.py` as `SAML_IDP_FILE` and `SAML_SP` and in `settings.json` which needs to be placed in a strange location `django_project/venv/lib/python3.10/site-packages/settings.json` (I suppose lib should in look for in the lib's directory not in general `site-packages` dir). 

For now I moved to implementation of OneLogin's library into my Django project, This wrapper looks very cool though, great work. Pity I couldn't get it to work!

**Comment by ngearhart** [comment]
Closing this as unresolved. Sorry that I could not help.
